name: Full update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  full-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          SRC_ORG: ${{ secrets.SRC_ORG }}
          DST_ORG: ${{ secrets.DST_ORG }}
        run: python mirror_github_org.py
